"""
convert rising_falling_int8.tflite into a .cpp/.h pair for compiling into ESP32 firmware.
run after build_quantized_tflite.py whenever the model changes.
"""

from __future__ import annotations

import argparse
from pathlib import Path

_SCRIPT_DIR = Path(__file__).resolve().parent
_DEFAULT_TFLITE = _SCRIPT_DIR / "rising_falling_int8.tflite"
_DEFAULT_OUT_DIR = _SCRIPT_DIR.parent / "embedded_rising_falling"


def tflite_to_cpp(data: bytes, array_name: str = "g_rising_falling_model") -> tuple[str, str]:
    header = f"""#pragma once

// auto-generated by export_embedded_model.py — do not edit by hand

#include <cstddef>

extern const unsigned char {array_name}[];
extern const unsigned int {array_name}_len;
"""

    lines = [f'// auto-generated by export_embedded_model.py — do not edit by hand\n']
    lines.append('#include "rising_falling_model.h"\n\n')
    lines.append(f'const unsigned char {array_name}[] = {{\n')
    row: list[str] = []
    for i, b in enumerate(data):
        row.append(f"0x{b:02x}")
        if len(row) >= 12:
            lines.append("  " + ", ".join(row) + ",\n")
            row = []
    if row:
        lines.append("  " + ", ".join(row) + ",\n")
    lines.append("};\n\n")
    lines.append(f"const unsigned int {array_name}_len = sizeof({array_name});\n")
    cpp = "".join(lines)
    return header, cpp


def main() -> int:
    ap = argparse.ArgumentParser(description="tflite flatbuffer -> C array for TFLM")
    ap.add_argument("--tflite", type=Path, default=_DEFAULT_TFLITE)
    ap.add_argument("--out-dir", type=Path, default=_DEFAULT_OUT_DIR)
    args = ap.parse_args()

    if not args.tflite.is_file():
        print(f"missing {args.tflite} — run build_quantized_tflite.py first")
        return 1

    data = args.tflite.read_bytes()
    args.out_dir.mkdir(parents=True, exist_ok=True)
    h, cpp = tflite_to_cpp(data)
    h_path = args.out_dir / "rising_falling_model.h"
    cpp_path = args.out_dir / "rising_falling_model.cpp"
    h_path.write_text(h, encoding="utf-8")
    cpp_path.write_text(cpp, encoding="utf-8")
    print(f"wrote {h_path} ({len(h)} bytes header text)")
    print(f"wrote {cpp_path} ({len(data)} bytes model -> C array)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
