#pragma once

// auto-generated by export_embedded_model.py — do not edit by hand

#include <cstddef>

extern const unsigned char g_rising_falling_model[];
extern const unsigned int g_rising_falling_model_len;
